[lesson 4] add file
gordano/js_practices pull request #5
Opened 2022-07-11 05:12 UTC by gordano

2022-07-11 08:22 UTC, fanisco requested changes

2022-07-11 08:22 UTC, fanisco commented on practices/p4/task2.js
> +    let isSameType = (ship, yard) => {
Определения функций лучше писать до их использования

2022-07-11 08:22 UTC, fanisco commented on practices/p4/task2.js
> +    this.repaint = function (ship, color) {
Должна ли тут быть проверка на тип корабля?

2022-07-11 08:22 UTC, fanisco commented on practices/p4/task2.js
> +    this.exchange = function (ship) {
Тут фактически ничего не происходит, инстанс корабля остается тот же самый

2022-07-12 08:06 UTC, fanisco commented on practices/p4/task2.js
> +    this.repaint = function (ship, color) {
Проверка на тип корабля так и не появилась =(

2022-07-12 08:06 UTC, fanisco commented on practices/p4/task2.js
> +    }
Раз метод становится публичным, тип верфи можно инкапсулировать внутри класса, чтобы не было необходимости его передавать:
```suggestion
    this.isSameType = (type) => {
        return type === this.type;
    }
```

2022-07-12 09:39 UTC, gordano commented on practices/p4/task2.js
> +    }
Справедливо. Исправил. Спасибо

2022-07-12 09:43 UTC, gordano commented on practices/p4/task2.js
> +    this.repaint = function (ship, color) {
Хех.  Добавил проверку на тип корабля при перекраске. Не могу оставить грустный смайлик без внимания ;)

Я трактовал эту строчку  задании иначе, а именно что верфям не важно что красить - главное чтобы оно плавало.

"Перекрашивать корабли - Можно красить любые корабли"

2022-07-13 13:27 UTC, fanisco commented on practices/p4/task2.js
> +    this.repaint = function (ship, color) {
Материал красящейся поверхности и состав самой краски может быть разным от типа к типу кораблей (=

2022-07-20 09:12 UTC, merged